baseURL = 'https://havekidsright.com/'
languageCode = 'en-us'
title = 'Have Kids Right!'
theme = 'ananke'
copyright = 'Wolf McNally'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
